BASE = "/h/u6/c9/01/wangwi18/winter24/csc413/project/"
SONGS_PATH = BASE + "/data/songs/songs/"
METADATA_PATH = BASE + "/data/birdsong_metadata.csv"
AUDIO_PATH = BASE + "/data/audio/"
SPECTROGRAM_PATH = BASE + "/data/spectrograms/"
PLOTS_DIR = BASE + "/plots/"