BASE = "/h/u6/c9/01/wangwi18/winter24/csc413/project/data/"
SONGS_PATH = BASE + "/songs/songs/"
METADATA_PATH = BASE + "/birdsong_metadata.csv"
AUDIO_PATH = BASE + "/audio/"
SPECTROGRAM_PATH = BASE + "/spectrograms/"